name: Deploy Frontend React

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build React Project
        run: |
          # Variable corregida a VITE_API_URL para coincidir con tu código
          echo "VITE_API_URL=${{ secrets.BACKEND_URL }}" >> .env.production
          npm run build

      - name: Compress Dist Folder
        run: tar -czf front.tar.gz -C dist .

      - name: Create Remote Temp Folder and Upload via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME_RUTA_GO }}
          key: ${{ secrets.PASSWORD_SSH }}
          port: 22
          source: "front.tar.gz"
          target: "/home/${{ secrets.USER_NAME_RUTA_GO }}/front_tmp/"

      - name: Deploy to Web Directory via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME_RUTA_GO }}
          key: ${{ secrets.PASSWORD_SSH }}
          port: 22
          script: |
            cd ~/front_tmp
            tar -xzf front.tar.gz
            rm front.tar.gz

            # Crear directorio web definitivo y mover los archivos estáticos
            mkdir -p /var/www/seminario1/rutago/
            cp -r * /var/www/seminario1/rutago/

            # Limpiar residuos temporales
            cd ~
            rm -rf ~/front_tmp
